version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  postgres: