
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: touristak
  username: lucas
  password: postgres

development:
  <<: *default
  database: touristaki_web_development

production:
  <<: *default
  database: touristaki_web_production
  username: funilaria
  password: <%= ENV['TOURISTAKI_WEB_DATABASE_PASSWORD'] %>
